package cmdb_meta

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateProjectParams creates a new CreateProjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCmdbMetaParams() *GetCmdbMetaParams {
	return &GetCmdbMetaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateProjectParamsWithTimeout creates a new CreateProjectParams object
// with the ability to set a timeout on a request.
func NewGetCmdbMetaParamsWithTimeout(timeout time.Duration) *GetCmdbMetaParams {
	return &GetCmdbMetaParams{
		timeout: timeout,
	}
}

// NewCreateProjectParamsWithContext creates a new CreateProjectParams object
// with the ability to set a context for a request.
func NewGetCmdbMetaParamsWithContext(ctx context.Context) *GetCmdbMetaParams {
	return &GetCmdbMetaParams{
		Context: ctx,
	}
}

// NewCreateProjectParamsWithHTTPClient creates a new CreateProjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCmdbMetaParamsWithHTTPClient(client *http.Client) *GetCmdbMetaParams {
	return &GetCmdbMetaParams{
		HTTPClient: client,
	}
}

/* CreateProjectParams contains all the parameters to send to the API endpoint
   for the create project operation.

   Typically these are written to a http.Request.
*/
type GetCmdbMetaParams struct {

	/* APIVersion.

	   The version of the API in yyyy-MM-dd format (UTC). For versioning information refer to /iaas/api/about
	*/
	APIVersion *string

	/* Body.

	   Project Specification instance
	*/
	ClassName  string
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCmdbMetaParams) WithDefaults() *GetCmdbMetaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCmdbMetaParams) SetDefaults() {
	// no default values defined for this parameter
}

func (o *GetCmdbMetaParams) WithClassName(className string) *GetCmdbMetaParams {
	o.SetClassName(className)
	return o
}

func (o *GetCmdbMetaParams) SetClassName(className string) {
	o.ClassName = className
}

// WithTimeout adds the timeout to the create project params
func (o *GetCmdbMetaParams) WithTimeout(timeout time.Duration) *GetCmdbMetaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create project params
func (o *GetCmdbMetaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create project params
func (o *GetCmdbMetaParams) WithContext(ctx context.Context) *GetCmdbMetaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create project params
func (o *GetCmdbMetaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create project params
func (o *GetCmdbMetaParams) WithHTTPClient(client *http.Client) *GetCmdbMetaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create project params
func (o *GetCmdbMetaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the create project params
func (o *GetCmdbMetaParams) WithAPIVersion(aPIVersion *string) *GetCmdbMetaParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the create project params
func (o *GetCmdbMetaParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WriteToRequest writes these params to a swagger request
func (o *GetCmdbMetaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// query param apiVersion
		var qrAPIVersion string

		if o.APIVersion != nil {
			qrAPIVersion = *o.APIVersion
		}
		qAPIVersion := qrAPIVersion
		if qAPIVersion != "" {

			if err := r.SetQueryParam("apiVersion", qAPIVersion); err != nil {
				return err
			}
		}
	}

	if err := r.SetPathParam("className", o.ClassName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
